// Generated by CoffeeScript 1.8.0
module.exports = {
  connections: {
    mongo: {
      database: 'NorthTexasPigeonDEV'
    }
  },
  email: {
    from: 'North Texas Pigeon <northtexaspigeon@gmail.com>',
    transportOptions: {
      service: 'Gmail',
      auth: {
        user: 'you@gmail.com',
        pass: 'yourgmailpass'
      },
      maxConnections: 20,
      maxMessages: Infinity
    },
    uploads: {
      url: 'http://uploads.ntpigeon.local'
    }
  }
};
